// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yidyomzfkrumghhdevmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZHlvbXpma3J1bWdoaGRldm1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjg0OTEsImV4cCI6MjA2NjY0NDQ5MX0.EMQuCfoUSfkj112gXoOmo_7_ejeP5vdkjokLK_TnMnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);